### ISSUE TITLE
Implement Interpolation Extension

### ISSUE THREAD

**Issue by jlewis91** [MichaelHatherly/CommonMark.jl#15]
> I can imagine there is a bit of a catch-22 situation here...libraries currently using Markdown implicitly rely upon the interpolation offered by the lib, so the absence of this feature limits drop-in adoption

Yeah, pretty much that. We'll have to implement it prior to consideration for stdlib otherwise it doesn't have feature parity with `Markdown` which I consider a requirement.

> Looking forward to seeing how this lib develops, feel free to tag me in any beginner level issues that may come up in this project

Not exactly a *beginner* level issue, but getting the interpolation syntax working is the only major outstanding thing. If you ever feel like looking into that one the best place to start is look at how the `$` math syntax is implemented and adapting that: https://github.com/MichaelHatherly/CommonMark.jl/blob/1acfbef49e2ccb90de2ee4260c7e1a7ad4e4c319/src/extensions/math.jl#L53-L103

_Originally posted by @MichaelHatherly in https://github.com/MichaelHatherly/CommonMark.jl/issues/14#issuecomment-787478997_

**Comment by jlewis91** [comment]
@MichaelHatherly Thanks for the nudge. I'll look into it, see how far I get. :)

**Comment by MichaelHatherly** [comment]
Closed in #16.
