### ISSUE TITLE
please bump the [compat] for JSON

### ISSUE THREAD

**Issue by JeffreySarnoff** [MichaelHatherly/CommonMark.jl#2]
The current version of [JSON.jl](https://github.com/JuliaIO/JSON.jl) is `1`.
Using an old version in [compat] can cause `ERROR: Unsatisfiable requirements` when there are other packages `added` that do not list the old version in thier [compat].
You can specify multiple versions, if there is reason to do so.

**Comment by MichaelHatherly** [comment]
> The current version of JSON.jl is `1`.

As far as I can tell JSON 1.0 hasn't been tagged in General yet? Or maybe I'm not looking in the right place?

> Using an old version in [compat] can cause `ERROR: Unsatisfiable requirements` when there are other packages `added` that do not list the old version in thier [compat].

Which particular packages are causing the conflict? `0.20.1` doesn't look that old to me: https://github.com/JuliaIO/JSON.jl/releases.

I'm still getting up to speed on the new pkg, so maybe I'm missing something here?

**Comment by JeffreySarnoff** [comment]
Oh, you are right that JSON has not released  v1.  The current version appears to be 0.21.  The way package version resolution/checking works now is that it works best when either the [compat] entry is given loosely (`JSON = "0"` or, in this case, `JSON = "0.2"` would also qualify) or the [compat] entry is given broadly, covering through the current version (`JSON = "0.20, 0.21"``).  There is even a bot which workds to keep these compat lines current with the general registry's information.  I find it easiest and most fool-proof to use `pkg = "0"` or `pkg = "1"`, other people list a number of relatively current versions.  Some generic details are [here](https://julialang.github.io/Pkg.jl/v1/compatibility/).  Because other packages that may depend on, say JSON, probably include the latest version in their [compat] (and maybe only that) if your [compat] omits it, there can be consternation within the package version resolution code.  It is widely understood that this is not desirable, and a goal is to keep the minimal number of versions of a package locally to allow things to resolve in as up-to-date a way as possible. Till then ...

As an aside, take a look at [JSON3.jl](https://github.com/quinnj/JSON3.jl). It has become the favorite of many over the past six months.  You are likely to find that it does what you need faster than JSON.jl and properly.  

It is good to see you back in Julia land.
