### ISSUE TITLE
Newline `\n` is not preserved in latex output for codeblocks

### ISSUE THREAD

**Issue by akels** [MichaelHatherly/CommonMark.jl#3]
I am currently trying to move from LaTeX to Markdown for writing an article which contains some code. For code blocks which get put into `verbatim` environment I found that `\n` is not preserved and as well `_` is being escaped with `\`, whereas in html output such things does not happen. MWE:
```
using CommonMark
markdown = Parser()
ast = markdown("""```
x_i = 1
y = 2
```""") 
```
`html(ast)` gives `"<pre><code>x_i = 1\ny = 2\n</code></pre>\n"` whereas `latex(ast)` is `"\\begin{verbatim}\nx\\_i = 1y = 2\n\\end{verbatim}\n" `.

**Comment by MichaelHatherly** [comment]
This is fixed in latest `master` I believe, I assume you're on `0.2.0`?

**Comment by akels** [comment]
Yes, I was on `v0.2.0`. Master indeed fixes the bug  :)

**Comment by MichaelHatherly** [comment]
I'll release a `0.3` sometime this week so you won't need to remain on master for too long.

**Comment by MichaelHatherly** [comment]
https://github.com/MichaelHatherly/CommonMark.jl/commit/98f42134300c2af7630e05f5fe62d9c38accb7eb will have the fixes you need @akels.
