### ISSUE TITLE
Interpolate a vector of items

### ISSUE THREAD

**Issue by fonsp** [MichaelHatherly/CommonMark.jl#30]
The `@md_str` from Markdown, and the `@htl` macro from https://github.com/MechanicalRabbit/HypertextLiteral.jl will render items one-by-one if you interpolate a vector or generator:

![Schermafbeelding 2021-12-16 om 12 37 31](https://user-images.githubusercontent.com/6933510/146364913-15cbcc28-7dcb-4613-a66d-93368523d904.png)

```julia
worlds = [HTML("<div>world $i</div>") for i in 1:3]
```

The `@cm_str` macro renders the vector itself. Is this intentional? Is there another way to render all items? (My solution right now is to wrap the array in `@htl("$(worlds)")` to turn it into a single HTML renderable.

**Comment by MichaelHatherly** [comment]
Yeah, probably just matching what `md` does here is most reasonable.

**Comment by MichaelHatherly** [comment]
Fixed in #32.
