### ISSUE TITLE
HypertextLiteral.jl + CommonMark.jl = 🤯

### ISSUE THREAD

**Issue by fonsp** [MichaelHatherly/CommonMark.jl#31]
I made a combination of [HypertextLiteral.jl](https://github.com/MechanicalRabbit/HypertextLiteral.jl) by @clarkevans and CommonMark.jl, and I think it is really cool!!

> ### [DEMO NOTEBOOK](https://htmlview.glitch.me/?https://gist.github.com/fonsp/29015dc6fd9438cd164a51fe3bef117d)

<details><summary>Screenshots</summary>

![Schermafbeelding 2021-12-16 om 13 17 09](https://user-images.githubusercontent.com/6933510/146370539-3c6245f7-c171-45d7-928d-083212569de8.png)

![Schermafbeelding 2021-12-16 om 13 15 48](https://user-images.githubusercontent.com/6933510/146370562-6636c73b-61a1-40d8-93c2-b631ba95af98.png)

</details>

# Features
The list of features is really simple to explain: it is everything that CommonMark gives, plus everything that HypertextLiteral gives! This includes:
- CommonMark! Markdown but less glitchy!
- Really flexible interpolation support with infinite nesting and syntax highlighting (since it is a `@md("""` macro instead of `md"""`)
- Interpolate Julia objects into `<script>` to automatically convert to JS literals
- Context-aware HTML escaping
- Automatic quote wrapping for HTML attributes
- Use a `Dict` or `NamedTuple` for the `style` attribute inside an HTML tag

# Implementation

Also cool: the code is extremely short!
```julia
macro md(expr)
	cm_parser = CommonMark.Parser()
	quote
		result = @htl($expr)
		htl_output = repr(MIME"text/html"(), result)

		$(cm_parser)(htl_output)
	end
end
```

It is essentially the `@htl` macro for HypertextLiteral.jl, but the result is passed through a CommonMark parser. This works, because:
- CommonMark allows raw HTML
- HypertextLiteral leaves literal content unchanged, so `hello *world*` appears exactly 

---

Let me know what you think! Perhaps it can be added to this package as a new macro, or we can make a new package.

**Comment by MichaelHatherly** [comment]
That's awesome. I'm quite surprised that commonmark's HTML handling is actually sufficient to parse `htl_output` correctly.

**Comment by MichaelHatherly** [comment]
Regarding including it here, I'd like to remove deps where possible since the eventual end goal is a standard lib. Might be a PlutoUI macro, though whether `@md` is actually "UI" is debatable I guess...

**Comment by fonsp** [comment]
That makes sense! I really hope it becomes a stdlib! I like the idea of including it in PlutoUI.

Let's continue testing it to see if there are any unforseen problems, and then release it!

**Comment by fonsp** [comment]
We will discuss this at the weekly pluto developers call in 1 hour: https://julialang.org/community/#events @MichaelHatherly @jeremiahpslewis feel free to join if you have time!

**Comment by MichaelHatherly** [comment]
https://github.com/MichaelHatherly/CommonMark.jl/blob/master/src/extensions/interpolation.jl#L121-L152 is the set of extensions that get used in `cm""` which is probably what you'd actually want to use in the "real" `@mdl` macro. It's an internal method so probably don't use it directly, we _could_ export a better named version of that one perhaps.

**Comment by fonsp** [comment]
FYI I made https://github.com/JuliaPluto/MarkdownLiteral.jl ! I am still wondering what the best name would be, my favourites are:
- `@md` (this is not used by any package yet: [1](https://juliahub.com/ui/Search?type=code&q=macro%20md&r=true) [2](https://juliahub.com/ui/Search?type=code&q=export%20.%2a%40md&r=true)), but it might be confusingly close to `md"""`
- `@markdown` ([also not taken](https://juliahub.com/ui/Search?type=code&q=macro%20markdown&r=true)) is probably my favourite because it is unintimidating and clear. But it does not capture the HTL magic
- `@markdownliteral` maybe? Long names are fine because we will eventually use a GUI button
- `@mdl` is accurate but something abstract to force people to remember

**Comment by MichaelHatherly** [comment]
Could go with `@mdx` since the syntax supported is _kind of_ like  https://mdxjs.com/ though not quite.

**Comment by lukeburns** [comment]
This is great, so much easier to interpolate in latex expressions!

**Comment by MichaelHatherly** [comment]
I'll close this issue now since there isn't much more needed here.
