### ISSUE TITLE
Indentation within HTML block with empty lines

### ISSUE THREAD

**Issue by fonsp** [MichaelHatherly/CommonMark.jl#42]
The following input:

```
asdf

<blockquote class="banner">
    <p>Hello world.</p>
</blockquote>
```

produces this output:

```html
<p>asdf</p>

<blockquote class="banner">
    <p>Hello world.</p>
</blockquote>
```

---

but if I add an empty line inside the block, the contents get escaped: 😥

```
asdf

<blockquote class="banner">

    <p>Hello world.</p>
</blockquote>
```

```html
<p>asdf</p>
<blockquote class="banner">
<pre><code>&lt;p&gt;Hello world.&lt;/p&gt;
</code></pre>
</blockquote>
```

**Comment by MichaelHatherly** [comment]
If we're inconsistent with https://spec.commonmark.org/dingus/ then we can adjust as needed, but I think we are probably replicating the expected behaviour of the reference implementation here.

**Comment by MichaelHatherly** [comment]
Consistent with upstream as far as I can tell, closing as wontfix.
