### ISSUE TITLE
Newlines disappearing from code blocks

### ISSUE THREAD

**Issue by bramtayl** [MichaelHatherly/CommonMark.jl#5]
Apologies if this is an option or intended. Newlines seem to be disappearing from code-blocks:

```
using CommonMark

markdown(stdout, Parser()("""
Docstring

\```jldoctest
julia> a = 1
1

julia> b = 2
2
\```
"""))
```

**Comment by MichaelHatherly** [comment]
Good catch, wasn't intended. Fix incoming shortly.

**Comment by MichaelHatherly** [comment]
Should be sorted @bramtayl, you needing a tag with this fix included, or are you happy working of `master` for now?

**Comment by bramtayl** [comment]
Um, there's not a huge rush because I'm still messing around with the PR to JuliaFormatter, but sooner rather than later would be great!

**Comment by MichaelHatherly** [comment]
I'll hold off for a few days then.
