### ISSUE TITLE
`benchmark/`: simplify

### ISSUE THREAD

**Issue by tfiers** [MichaelHatherly/CommonMark.jl#61]
re the `benchmark/` dir I introduced in
- #59 

Just jotting down some ideas to make that better.
Mostly: simplify it.
- [ ] Only one project (Literate and CommonMark can be in the same project, it's okay)
- [ ] Only one benchmarking script (it can test everything: both startup latency (TTFParse etc), and full compiled speed)
	- (Right now it's setup for 'possible future' other benchmarking scripts, but let's be realistic)
- Only one .md file? It's nice that github auto-opens the ReadMe when opening the benchmarks folder on GitHub. So maybe that could be the output file generated with Literate.jl from the benchmarking script.\
 Or two markdown files (ReadMe.md, benchmark.md), that's fine too

Misc:
- [ ] Print `now()` (yes you can look at commit date, but that's a bit hidden and could be != run date)

Also, maybe:
- [ ] add it to CI, to track performance regressions.
	- You can then flip through the 'History' of the benchmark markdown file on github, to see how timings change
		- Not ideal. Also not automated

**Comment by MichaelHatherly** [comment]
This is quite old now, @tfiers do you plan to work on this.

**Comment by tfiers** [comment]
No, feel free to archive
