### ISSUE TITLE
Migrate to PrecompileTools

### ISSUE THREAD

**Issue by davidanthoff** [MichaelHatherly/CommonMark.jl#64]
Would be great if this package could be migrated from SnoopPrecompile to PrecompileTools. For various reasons we can't ship packages that use SnoopPrecompile in the VS Code extension, but everything works fine with PrecompileTools. JuliaFormatter uses CommonMark, and so at the moment we are blocked from shipping the latest formatting code in the extension until CommonMark is also migrated to PrecompileTools. https://github.com/domluna/JuliaFormatter.jl/pull/710 has an example what needs to be done, I think it is fairly easy.

**Comment by MichaelHatherly** [comment]
Yeah, it's on the list of todos. Should be able to sort this today I'd think @davidanthoff.

**Comment by MichaelHatherly** [comment]
Will be included in https://github.com/JuliaRegistries/General/pull/82413.

**Comment by davidanthoff** [comment]
Hurray, thanks!
