### ISSUE TITLE
Discoverability on JuliaHub: should be easier to find when searching for "Markdown"

### ISSUE THREAD

**Issue by nsajko** [MichaelHatherly/CommonMark.jl#72]
Currently the description of this repo is:

> A CommonMark-compliant parser for Julia.

AFAIK JuliaHub adopts the repo description as the package description, updating the entry whenever you make a release. AFAIK the package description influences the JuliaHub package search results.

I think adding "Markdown" into your repo description would help the package be more discoverable via JuliaHub, so I propose this repo description:

> A CommonMark-compliant Markdown parser for Julia.

**Comment by MichaelHatherly** [comment]
Thanks, changed.
